language: node_js
node_js:
  - "7"

compiler: gcc
sudo: false

os:
  - linux

osx_image: xcode8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

before_install:
  - npm config set python `which python`
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="gcc-4.8";
      export CXX="g++-4.8";
      export LINK="gcc-4.8";
      export LINKXX="g++-4.8";
    fi
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      brew install homebrew/science/vips --with-webp --with-graphicsmagick;
    fi
  - nvm --version
  - node --version
  - npm --version
  - gcc --version
  - g++ --version

install:
  - npm install mango-cli
  - node node_modules/mango-cli/bin/mango install

script:
  - node node_modules/mango-cli/bin/mango build

env:
  global:
    secure: "F6oVRfmtJOcZiCFtt+mGdTXCZGYmwooYhi1Rt6gLkiANu+TpvnZcfy3ELvmM8nkRXNJADKo7u+C61dvAVxiGWU+EJIthGBAAcsgrOwZwyu9vxbO2oFpRIwYApfbnj5cmrH3EZnUGzm+Wi2mxf2mEngUEcpD+6hmScIBGhDjvKd4UVSzPrLWO9U9wUyrvUjDraaM52LgOtZX4DExL2fkQ77dVt3TqtA4seyNqm+3SqCosqbP/1zXXKeALbEahUz2rxaAo7Ro7vJYLrQgahNgHQYmRAT1laSAmEqjeme6cXsI4rEcFirYvtpFVBQFo7kMhTz+wN/t5237CV6HiQUX9tN/TxZfkPqLGQNY+3j7ztvMn3fqW3zlMOjxEQJ60Dl7J93ZkfZDllxyLRf4Rp26WjhfT8MG58/kQyd+MbBc74PLAytl/QTJPMQMJBMUkuzbQkP9Fp72GfNDSNlRt0QLaSRB76fJLwmo6/vwyMyN9lla1FLG8AzQg1kgtSo/xwWeNEK/SKYZTJw10tZu+bKidA+sZu2yMvttCS4CBob8SlJdVCsJUsdYAFrRygT2tp22Pz/D0bYBlYb3lv3RkKHJh9RNnlw0gRu9n5KehVBpN4wU9uSWVWGCLTICSi3jnwuczVCE3cnbZCyfypjE3KQkqpSAkdG1U4bCOpscUMZUp4Bc=" # GH_TOKEN=xyz123

after_success:
  - GIT_REPO="https://$GH_TOKEN@github.com/Onset/isste.git"
  - cd dist
  - git init
  - git config user.email "ci@travis-ci.org"
  - git config user.name "Travis CI"
  - git add .
  - git commit -m "Deploy"
  - git push --force --quiet $GIT_REPO master:gh-pages

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules
